### ISSUE TITLE
Unable to run code

### ISSUE THREAD

**Issue by superamc2018** [rikardolajos/clouds#2]
Exception occurs while running source code since texture files are missing in **res** directory.
Kindly provide all the texture files.

**Comment by rikardolajos** [comment]
There is another branch called _with_libs_and_resources_. Try that one.

**Comment by superamc2018** [comment]
Thanks Rikard, I will try that and will let you know.

**Comment by superamc2018** [comment]
Hi Rikard,

The application is now running without errors. But it doesn't look like the one shown in the youtube video:
https://www.youtube.com/watch?v=V-Ij1HPSkb8

Attached is the image for output on my machine.

![clouds](https://user-images.githubusercontent.com/54579604/63848372-568b3680-c9ad-11e9-8061-bb73c34f5501.png)
 

Could you please guide me what might be going wrong?

**Comment by rikardolajos** [comment]
The projection matrix is wrong. It seems like a degree/radians mixup for the field of view. On line 39 in camera.cpp remove the conversion to radians. Replacing with:
`glm::perspective(c->fov, (float)c->width / (float)c->height, c->z_near, c->z_far);`

I am also getting some weird structure in the clouds which shouldn't be there. It is probably something with the step length in the ray marcher. You can play around with the `delta_large `and `delta_small` in `resolve_noise.frag` to see the difference. Uncommenting adaptive step length on line 198 in `resolve_noise.frag` should give you higher frame rates as well.

**Comment by superamc2018** [comment]
Thanks Rikard. I can now see cloud shapes at least, though there are some glitches visible in clouds. I will adjust `delta_large `and `delta_small` to see if it removes the glitches.

**Comment by superamc2018** [comment]
Hi Rikard,
After adjusting values of `delta_large` and `delta_small`, I could get rid of glitches. 
Thanks a lot for your help. :-)

**Comment by rikardolajos** [comment]
Good to hear!
